# Generated by Django 6.0 on 2026-03-03 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_full_name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20)),
                ('contact_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('disease', models.CharField(max_length=255)),
                ('treating_doctor', models.CharField(max_length=255)),
                ('treatment_description', models.TextField()),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('required_funding', models.DecimalField(decimal_places=2, max_digits=12)),
                ('campaign_description', models.TextField()),
                ('urgency_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('HOSPITAL_VERIFIED', 'Hospital Verified'), ('FUNDED', 'Funded')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.hospital')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='medical_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('medical_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='medical_cases.medicalcase')),
            ],
        ),
    ]
