# Generated by Django 6.0 on 2026-03-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_cases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalcase',
            name='campaign_description',
        ),
        migrations.RemoveField(
            model_name='medicalcase',
            name='urgency_level',
        ),
        migrations.AddField(
            model_name='medicalcase',
            name='annual_family_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='medicalcase',
            name='employment_status',
            field=models.CharField(choices=[('Salaried', 'Salaried'), ('Self-employed', 'Self-employed'), ('Daily wage', 'Daily wage'), ('Unemployed', 'Unemployed'), ('Retired', 'Retired')], default='Unemployed', max_length=20),
        ),
        migrations.AddField(
            model_name='medicalcase',
            name='family_members_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='medicalcase',
            name='government_scheme_enrolled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='document_type',
            field=models.CharField(choices=[('MEDICAL', 'Medical Document'), ('FINANCIAL', 'Financial Document')], default='MEDICAL', max_length=20),
        ),
    ]
