# Generated by Django 6.0 on 2026-03-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_cases', '0002_remove_medicalcase_campaign_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalcase',
            name='ai_score',
            field=models.IntegerField(default=0),
        ),
    ]
