# Generated by Django 6.0.2 on 2026-03-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_cases', '0003_medicalcase_ai_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalcase',
            name='ai_confidence_level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='medicalcase',
            name='ai_credibility_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalcase',
            name='ai_detailed_analysis',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalcase',
            name='ai_processing_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='medicalcase',
            name='ai_recommendation',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='medicalcase',
            name='ai_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalcase',
            name='ai_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='extracted_text',
            field=models.TextField(blank=True),
        ),
    ]
