# Generated by Django 6.0.2 on 2026-03-03 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_cases', '0004_medicalcase_ai_confidence_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalcase',
            name='hospital_mail_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicalcase',
            name='hospital_mail_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalcase',
            name='university_mail_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicalcase',
            name='university_mail_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
