# Generated by Django 6.0.2 on 2026-03-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_cases', '0005_medicalcase_hospital_mail_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalcase',
            name='hospital_reply_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalcase',
            name='hospital_reply_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicalcase',
            name='hospital_reply_received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
