# Generated by Django 6.0.2 on 2026-02-28 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=255)),
                ('hospital_registration_number', models.CharField(max_length=255)),
                ('official_email', models.EmailField(max_length=254)),
                ('official_phone_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('registration_certificate_file', models.FileField(upload_to='hospital_certificates/')),
                ('verification_status', models.CharField(default='pending', max_length=20)),
                ('is_verified_by_admin', models.BooleanField(default=False)),
                ('is_suspended', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
