# Generated by Django 6.0.2 on 2026-03-01 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_date_of_birth', models.DateField()),
                ('aadhar_number', models.CharField(max_length=12, unique=True)),
                ('disease_name', models.CharField(max_length=100)),
                ('diagnosis_date', models.DateField()),
                ('doctor_registration_number', models.CharField(max_length=100)),
                ('estimated_total_Cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_required', models.DecimalField(decimal_places=2, max_digits=10)),
                ('insurance_available', models.BooleanField(default=False)),
                ('prescription_document', models.FileField(upload_to='prescriptions/')),
                ('medical_report_document', models.FileField(upload_to='medical_reports/')),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('ai_risk_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('duplicate_case', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
